####  Import Required libraries

In [4]:
import pandas as pd
import numpy as np 
from textblob import TextBlob
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
import nltk
import string
import spacy

#### Loading a Dataset 

In [5]:
dataset = pd.read_csv("C:/Users/Admin/NLP_Project/Text_Preprocessing and Classification/Movies_review_dataset/IMDB Dataset.csv")
dataset = dataset.iloc[:50]
print(dataset)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
5   Probably my all-time favorite movie, a story o...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing, fresh & innovative i...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Boll's work but then ag...  negative
13  The cast played Shakespeare.<br /><br />Shakes...  negative
14  This a fantastic movie of three pris

#### Convert Uper case into lower case of dataset

In [6]:
dataset['review'] = dataset['review'].str.lower()
# print(dataset)

#### Remove HTML tags from text data ( Review column )

In [7]:
def remove_htmltag(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',text)

dataset['review'] = dataset['review'].apply(remove_htmltag)
# print(dataset)

#### Remove URLS or URLS tags from text data ( Review column )

In [8]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

dataset['review'] = dataset['review'].apply(remove_url)
# print(dataset)

#### Remove Puntuation from text data ( Review column ) 

In [9]:
def remove_punctuation(text):
    return text.translate(str.maketrans('','', string.punctuation))

dataset['review'] = dataset['review'].apply(remove_punctuation)
print(dataset)

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production the filming tech...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically theres a family where a little boy j...  negative
4   petter matteis love in the time of money is a ...  positive
5   probably my alltime favorite movie a story of ...  positive
6   i sure would like to see a resurrection of a u...  positive
7   this show was an amazing fresh  innovative ide...  negative
8   encouraged by the positive comments about this...  negative
9   if you like original gut wrenching laughter yo...  positive
10  phil the alien is one of those quirky films wh...  negative
11  i saw this movie when i was about 12 when it c...  negative
12  so im not a big fan of bolls work but then aga...  negative
13  the cast played shakespeareshakespeare losti a...  negative
14  this a fantastic movie of three pris

In [10]:
def spellchecker(text):
    new_df = TextBlob(text)
    return new_df.correct().string

dataset['review'] = dataset['review'].apply(spellchecker)
print(dataset)

                                               review sentiment
0   one of the other reviews has mentioned that af...  positive
1   a wonderful little production the filling tech...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there a family where a little boy ja...  negative
4   letter matters love in the time of money is a ...  positive
5   probably my alliee favorite movie a story of h...  positive
6   i sure would like to see a resurrection of a u...  positive
7   this show was an amazing fresh  innovative ide...  negative
8   encouraged by the positive comments about this...  negative
9   if you like original gut wrenching laughter yo...  positive
10  phil the alien is one of those quickly films w...  negative
11  i saw this movie when i was about 12 when it c...  negative
12  so in not a big fan of balls work but then aga...  negative
13  the cast played shakespeareshakespeare lost ap...  negative
14  this a fantastic movie of three pris

In [11]:
# stopwords.words('english')

In [12]:
def remove_stopwords(text):
    new_text = []
    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append(" ")
        else:
            new_text.append(word)
    return ' '.join(new_text)

dataset['review'] = dataset['review'].apply(remove_stopwords)
print(dataset)

                                               review sentiment
0   one       reviews   mentioned     watching   1...  positive
1     wonderful little production   filling techni...  positive
2     thought       wonderful way   spend time    ...  positive
3   basically     family     little boy jake think...  negative
4   letter matters love     time   money     usual...  positive
5   probably   alliee favorite movie   story   hel...  positive
6     sure would like   see   resurrection       d...  positive
7     show     amazing fresh innovative idea      ...  negative
8   encouraged     positive comments     film     ...  negative
9       like original gut wrenching laughter     l...  positive
10  phil   alien   one     quickly films     humou...  negative
11    saw   movie         12     came     recall  ...  negative
12          big fan   balls work         many     ...  negative
13    cast played shakespeareshakespeare lost appr...  negative
14      fantastic movie   three prisoner

In [13]:
# def words_token(text):
#     token = spacy.load('en_core_web_sm')
#     return token(text)

# dataset['review'] = dataset['review'].apply(words_token)
# print(dataset)

In [14]:
def stem_words(text):
    stemmer = PorterStemmer()
    return ' '.join([stemmer.stem(word) for word in text.split()])

dataset['review'] = dataset['review'].apply(stem_words)
print(dataset)

                                               review sentiment
0   one review mention watch 1 oz episod hook righ...  positive
1   wonder littl product fill techniqu assum oldti...  positive
2   thought wonder way spend time hot summer weeke...  positive
3   basic famili littl boy jake think combin close...  negative
4   letter matter love time money usual stun film ...  positive
5   probabl allie favorit movi stori helpless sacr...  positive
6   sure would like see resurrect date seahunt ser...  positive
7   show amaz fresh innov idea first tire first 7 ...  negative
8   encourag posit comment film look forward watch...  negative
9   like origin gut wrench laughter like movi youn...  positive
10  phil alien one quickli film humour base around...  negative
11  saw movi 12 came recal cari scene big bird eat...  negative
12  big fan ball work mani enjoy movi postal mayb ...  negative
13  cast play shakespeareshakespear lost appreci t...  negative
14  fantast movi three prison becom famo

In [15]:
def words_token(text):
    token = spacy.load('en_core_web_sm')
    return token(text)

dataset['review'] = dataset['review'].apply(words_token)
print(dataset)

                                               review sentiment
0   (one, review, mention, watch, 1, oz, episod, h...  positive
1   (wonder, littl, product, fill, techniqu, assum...  positive
2   (thought, wonder, way, spend, time, hot, summe...  positive
3   (basic, famili, littl, boy, jake, think, combi...  negative
4   (letter, matter, love, time, money, usual, stu...  positive
5   (probabl, allie, favorit, movi, stori, helples...  positive
6   (sure, would, like, see, resurrect, date, seah...  positive
7   (show, amaz, fresh, innov, idea, first, tire, ...  negative
8   (encourag, posit, comment, film, look, forward...  negative
9   (like, origin, gut, wrench, laughter, like, mo...  positive
10  (phil, alien, one, quickli, film, humour, base...  negative
11  (saw, movi, 12, came, recal, cari, scene, big,...  negative
12  (big, fan, ball, work, mani, enjoy, movi, post...  negative
13  (cast, play, shakespeareshakespear, lost, appr...  negative
14  (fantast, movi, three, prison, becom

In [16]:
nlp = spacy.load("en_core_web_sm")

def lemma(text):
    doc = nlp(text)
    lemmatized_tokens = [] 
    for token in doc:
        if token.pos_ == "VERB":
            lemmatized_tokens.append(token.lemma_)
        else:
            lemmatized_tokens.append(token.text)
    return " ".join(lemmatized_tokens)

dataset['review'] = dataset['review'].apply(lemma)
print(dataset)
    

                                               review sentiment
0   one review mention watch 1 oz episod hook righ...  positive
1   wonder littl product fill techniqu assum oldti...  positive
2   think wonder way spend time hot summer weekend...  positive
3   basic famili littl boy jake think combin close...  negative
4   letter matter love time money usual stun film ...  positive
5   probabl allie favorit movi stori helpless sacr...  positive
6   sure would like see resurrect date seahunt ser...  positive
7   show amaz fresh innov idea first tire first 7 ...  negative
8   encourag posit comment film look forward watch...  negative
9   like origin gut wrench laughter like movi youn...  positive
10  phil alien one quickli film humour base around...  negative
11  see movi 12 come recal cari scene big bird eat...  negative
12  big fan ball work mani enjoy movi postal mayb ...  negative
13  cast play shakespeareshakespear lose appreci t...  negative
14  fantast movi three prison becom famo

In [17]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder()

In [18]:
enc = enc.fit_transform(dataset[['review']]).toarray()
print(enc)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [25]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(1,3))

In [26]:
new = cv.fit_transform(dataset['review'])
print(new)

  (0, 7930)	1
  (0, 9356)	1
  (0, 6918)	1
  (0, 12386)	3
  (0, 8143)	5
  (0, 3319)	2
  (0, 5176)	1
  (0, 9394)	2
  (0, 3474)	1
  (0, 4886)	1
  (0, 6945)	1
  (0, 4068)	2
  (0, 11269)	1
  (0, 10765)	2
  (0, 1455)	1
  (0, 11954)	1
  (0, 9677)	1
  (0, 12215)	4
  (0, 9996)	1
  (0, 12747)	2
  (0, 4561)	1
  (0, 11829)	1
  (0, 10095)	4
  (0, 3659)	1
  (0, 4976)	1
  :	:
  (49, 8530)	1
  (49, 8560)	1
  (49, 4023)	1
  (49, 4630)	1
  (49, 7430)	1
  (49, 6399)	1
  (49, 2646)	1
  (49, 8853)	1
  (49, 9020)	1
  (49, 5930)	1
  (49, 10046)	1
  (49, 9631)	1
  (49, 6291)	1
  (49, 310)	1
  (49, 5633)	1
  (49, 4877)	1
  (49, 4312)	1
  (49, 4174)	1
  (49, 518)	1
  (49, 11379)	1
  (49, 12970)	1
  (49, 1960)	1
  (49, 12575)	1
  (49, 6413)	1
  (49, 7)	1


In [27]:
print(cv.vocabulary_)

{'one': 7930, 'review': 9356, 'mention': 6918, 'watch': 12386, 'oz': 8143, 'episod': 3319, 'hook': 5176, 'right': 9394, 'exactli': 3474, 'happen': 4886, 'metr': 6945, 'first': 4068, 'thing': 11269, 'strike': 10765, 'brutal': 1455, 'unflinch': 11954, 'scene': 9677, 'violenc': 12215, 'set': 9996, 'word': 12747, 'go': 4561, 'trust': 11829, 'show': 10095, 'faint': 3659, 'heart': 4976, 'timid': 11545, 'pull': 8881, 'punch': 8884, 'regard': 9167, 'drug': 3012, 'sex': 10019, 'hardwar': 4940, 'classic': 1907, 'use': 12073, 'call': 1529, 'nicknam': 7694, 'give': 4476, 'onward': 8057, 'maximum': 6820, 'secur': 9821, 'state': 10595, 'penitentiari': 8286, 'focus': 4132, 'mainli': 6594, 'emerald': 3149, 'citi': 1883, 'experiment': 3555, 'section': 9818, 'prison': 8762, 'cell': 1689, 'glass': 4534, 'front': 4228, 'face': 3608, 'inward': 5623, 'privaci': 8771, 'high': 5060, 'agenda': 330, 'em': 3143, 'home': 5133, 'manyaryan': 6753, 'muslin': 7491, 'gangsta': 4321, 'nation': 7541, 'christian': 1849, 

In [28]:
print(new[0:].toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(dataset['review']).toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.04213849, 0.        ,
        0.        ],
       [0.        , 0.10695229, 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[4.23867845 3.14006616 4.23867845 ... 4.23867845 4.23867845 4.23867845]
['0510' '10' '100' ... 'younger' 'zellweg' 'zombieok']
